### ISSUE TITLE
StdTimeFilter' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by makeitrad** [akatz-ai/ComfyUI-Depthflow-Nodes#19]
Started to get this one today after the latest ComfyUI update. Tried uninstall and using the FIX in manager but no love.
This is on Linux Ubuntu 22.04 LTS w/ 4090 

THX in advance Akatz!

```
Traceback (most recent call last):
  File "/home/zvi/ComfyUI/nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zvi/ComfyUI/custom_nodes/ComfyUI-Depthflow-Nodes/__init__.py", line 8, in <module>
    from .src.motion.depthflow_motion_components import DepthflowMotionSine, DepthflowMotionCosine, DepthflowMotionLinear, DepthflowMotionExponential, DepthflowMotionArc, DepthflowMotionSetTarget
  File "/home/zvi/ComfyUI/custom_nodes/ComfyUI-Depthflow-Nodes/src/motion/depthflow_motion_components.py", line 1, in <module>
    from .depthflow_motion_base import DepthflowMotion, Target
  File "/home/zvi/ComfyUI/custom_nodes/ComfyUI-Depthflow-Nodes/src/motion/depthflow_motion_base.py", line 2, in <module>
    from DepthFlow.Motion import Preset
  File "/home/zvi/miniconda3/envs/comfy4/lib/python3.10/site-packages/DepthFlow/__init__.py", line 2, in <module>
    from Broken import BrokenProject
  File "/home/zvi/miniconda3/envs/comfy4/lib/python3.10/site-packages/Broken/__init__.py", line 63, in <module>
    class Runtime:
  File "/home/zvi/miniconda3/envs/comfy4/lib/python3.10/site-packages/Broken/__init__.py", line 117, in Runtime
    Interactive: bool = sys.stdout.isatty()
AttributeError: 'StdTimeFilter' object has no attribute 'isatty'

Cannot import /home/zvi/ComfyUI/custom_nodes/ComfyUI-Depthflow-Nodes module for custom nodes: 'StdTimeFilter' object has no attribute 'isatty'
```

**Comment by akatz-ai** [comment]
Hey @makeitrad, my buddy Cyncratic tried downgrading the depthflow version to 1.0.3 using the latest comfyui beta. If you're able to use that node version it should hopefully still work. I'm out traveling in Japan for another week but when I get back I'll install the latest comfyui beta version and see if I can't fix it.

**Comment by makeitrad** [comment]
Thanks for the workaround @akatz-ai. Ill give this a shot and see if it works. Im actually not on the beta of ConmfyUI just the frontend. Don't think the frontend will make a difference however Ill turn that off as well and see if that fixes things. Safe travels and have fun in Japan! Thanks for all you do!

**Comment by aiXander** [comment]
Faced a similar issue and fixed it by upgrading ComfyUI Manager which now has this property hardcoded:
https://github.com/ltdrdata/ComfyUI-Manager/blob/58847298be7fd1c7dbba7a7670a7cd999d7900f9/prestartup_script.py#L196

**Comment by makeitrad** [comment]
> Faced a similar issue and fixed it by upgrading ComfyUI Manager which now has this property hardcoded: https://github.com/ltdrdata/ComfyUI-Manager/blob/58847298be7fd1c7dbba7a7670a7cd999d7900f9/prestartup_script.py#L196

Thanks Xander

**Comment by Tremeschin** [comment]
The wonders of [monkey patching](https://github.com/ltdrdata/ComfyUI-Manager/blob/58847298be7fd1c7dbba7a7670a7cd999d7900f9/prestartup_script.py#L275).. 😆

Yea, that's a miss on their implementation of `ComfyUIManagerLogger` not matching [stdlib](https://docs.python.org/3/library/sys.html#sys.stdout), for catching `print` logs

Looks like they fixed a couple months ago in https://github.com/ltdrdata/ComfyUI-Manager/pull/790 and https://github.com/ltdrdata/ComfyUI-Manager/commit/0e4f1713a4828de1358cda9e05a86f832f8f8dae, so yes, updating ComfyUI Manager with their fix is the way here 🙂

**Comment by akatz-ai** [comment]
Closing due to fix available in latest versions of ComfyUI Manager after https://github.com/ltdrdata/ComfyUI-Manager/pull/790
