### ISSUE TITLE
Exception: CreateWindow failed

### ISSUE THREAD

**Issue by green21st** [akatz-ai/ComfyUI-Depthflow-Nodes#20]
2024-12-04T09:02:21.436011 - !!! Exception during processing !!! CreateWindow failed
2024-12-04T09:02:21.443010 - Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.2\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Depthflow-Nodes\src\depthflow.py", line 293, in apply_depthflow
    scene = CustomDepthflowScene(
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Depthflow-Nodes\src\depthflow.py", line 59, in __init__
    DepthScene.__init__(self, **kwargs)
  File "<attrs generated init DepthFlow.Scene.DepthScene>", line 101, in __init__
    self.__attrs_post_init__()
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\Broken\Core\__init__.py", line 504, in __attrs_post_init__
    method(self)
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\ShaderFlow\Scene.py", line 120, in __post__
    self._build()
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\ShaderFlow\Scene.py", line 138, in _build
    self.init_window()
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\ShaderFlow\Scene.py", line 495, in init_window
    self.window = importlib.import_module(module).Window(
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\moderngl_window\context\headless\window.py", line 25, in __init__
    self.init_mgl_context()
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\moderngl_window\context\headless\window.py", line 41, in init_mgl_context
    self._ctx = moderngl.create_standalone_context(
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\moderngl\__init__.py", line 2304, in create_standalone_context
    return create_context(standalone=True, **kwargs)
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\moderngl\__init__.py", line 2254, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "D:\ComfyUI-aki-v1.2\python\lib\site-packages\glcontext\__init__.py", line 69, in create
    return wgl.create_context(**kwargs)
Exception: CreateWindow failed

2024-12-04T09:02:21.445011 - Prompt executed in 13.61 seconds

After some custom nodes updated, I've got this error. I have no idea what has changed. Help, please!

**Comment by akatz-ai** [comment]
Hi @green21st , please provide your full comfyui.log file to help with debugging. It should be available (based on your path info) at "D:\ComfyUI-aki-v1.2\comfyui.log"
