### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by lunatico67** [akatz-ai/ComfyUI-Depthflow-Nodes#21]
Hi
File "C:\Users\Luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Depthflow-Nodes\__init__.py", line 8, in <module>
    from .src.motion.depthflow_motion_components import DepthflowMotionSine, DepthflowMotionCosine, DepthflowMotionLinear, DepthflowMotionExponential, DepthflowMotionArc, DepthflowMotionSetTarget
  File "C:\Users\Luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Depthflow-Nodes\src\motion\depthflow_motion_components.py", line 1, in <module>
    from .depthflow_motion_base import DepthflowMotion, Target
  File "C:\Users\Luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Depthflow-Nodes\src\motion\depthflow_motion_base.py", line 2, in <module>
    from DepthFlow.Motion import Preset
ModuleNotFoundError: No module named 'DepthFlow'

Cannot import C:\Users\Luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Depthflow-Nodes module for custom nodes: No module named 'DepthFlow'

**Comment by Leoceleste** [comment]
same problem, every dependencies are installed, the nodes are in the correct location but comfy tells me that import failed. weird

**Comment by bachgroup** [comment]
Same for me guys even with the Comfyui Manager ...

**Comment by akatz-ai** [comment]
I think this may be related to an environment-based issue, are there any additional error messages besides "No module named 'Depthflow'" earlier in the debug logs? 
(fyi If you want to test out the node pack and be sure it will work with your setup I recommend trying out my [environment manager tool](https://github.com/akatz-ai/ComfyUI-Environment-Manager), and refer to these [instructions](https://github.com/akatz-ai/ComfyUI-Depthflow-Nodes/tree/main?tab=readme-ov-file#%EF%B8%8F-custom-environment) to grab the depthflow environment)

**Comment by bachgroup** [comment]
Hey Akatz , i just retry the installation and everything work fine ! I don't know if you have done something but thank you for your amazing work and your help. 
Have amazing new year !

**Comment by lunatico67** [comment]
Hi
Akatz thanks for your help.
I have the portable version of comfyui installed, I am not computer literate but I think it is not possible to create an environment in the portable version?
When installing the DepthFlow requirements this error appears at the end, I don't know if it is important:
error: uninstall-no-record-file

× Cannot uninstall moderngl None
╰─> The package's contents are unknown: no RECORD file was found for moderngl.

hint: You might be able to recover from this via: pip install --force-reinstall --no-deps moderngl==5.10.0

C:\Users\luna\Documents\ComfyUI_windows_portable>

When I open comfyui I get this error about DepthFlow:
xFormers not available
Traceback (most recent call last):
  File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2092, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Depthflow-Nodes\__init__.py", line 8, in <module>
    from .src.motion.depthflow_motion_components import DepthflowMotionSine, DepthflowMotionCosine, DepthflowMotionLinear, DepthflowMotionExponential, DepthflowMotionArc, DepthflowMotionSetTarget
  File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Depthflow-Nodes\src\motion\depthflow_motion_components.py", line 1, in <module>
    from .depthflow_motion_base import DepthflowMotion, Target
  File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Depthflow-Nodes\src\motion\depthflow_motion_base.py", line 2, in <module>
    from DepthFlow.Motion import Preset
ModuleNotFoundError: No module named 'DepthFlow'

Cannot import C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Depthflow-Nodes module for custom nodes: No module named 'DepthFlow'

Best

**Comment by lunatico67** [comment]
File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Depthflow-Nodes\__init__.py", line 8, in <module>
    from .src.motion.depthflow_motion_components import DepthflowMotionSine, DepthflowMotionCosine, DepthflowMotionLinear, DepthflowMotionExponential, DepthflowMotionArc, DepthflowMotionSetTarget
  File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Depthflow-Nodes\src\motion\depthflow_motion_components.py", line 1, in <module>
    from .depthflow_motion_base import DepthflowMotion, Target
  File "C:\Users\luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Depthflow-Nodes\src\motion\depthflow_motion_base.py", line 2, in <module>
    from DepthFlow.Motion import Preset
ModuleNotFoundError: No module named 'DepthFlow'

**Comment by hobinrude** [comment]
Hi @akatz-ai, I also had a bumpy ride installing with manager. After initial failed import I used "try-fix-it" and watched terminal. CMake was missing some dev libraries and couldn't build wheel for **imgui-bundle**. Had to repeat the cycle 4 times because silly installer only mentions 1 missing library each time LOL These were the missing packages in my case:

libxrandr-dev
libxinerama-dev
libxcursor-dev
libxi-dev

After installing all 4, I could finally get the nodes to install properly and see no errors when importing. Hope it helps :)

**Comment by lunatico67** [comment]
Hi hobinrude.
Did you install all four before installing DepthFlow or after?
How did you install all four?

**Comment by hobinrude** [comment]
I first installed with manager but nodes were throwing import error on restart. The terminal stdout has provided the useful clues. I added missing dev-libraries with apt inatall in my case but it depends on the OS.

**Comment by lunatico67** [comment]
Thanks for the help but I don't understand anything, I'm not a computer scientist.

**Comment by hobinrude** [comment]
Neither am I, but when I encounter an error, I check logs for clues and it helps me solve 99% of the problems. If you expect more specific help you should at least provide us with the relevant information about the error. It can be found in terminal output displayed either during the process of installing/try-fix-iting the nodes and/or during restarting ComfyUI. It is next to impossible to provide any relevant help while we don't even know what the problem is. Also AFAIK, providing error logs is mandatory by the rules of issue reporting. The fragment you posted is not really telling much. Something must have gone wrong before that. Uninstall the node and start over. Run install again, check terminal output and look if any errors were reported (ctrl-c/ctrl-v relevant fragment to file.txt), then restart ComfyUI and check terminal again, then hit try-fix-it in manager and check terminal again. This is how I troubleshoot any errors I stumble upon ;)
